spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /