spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
    username: root
    password: 12345
  liquibase:
    parameters:
      textColumnType: VARCHAR(250)
    contexts: nonprod

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method
